name: Check Coding Style
on:
  push:
  workflow_dispatch:

jobs:
  check-coding-style:
    name: Check Coding Style
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: ./    # Replace this with hugoschool/cs2-action@v1
        with:
          path: tests/valid
